// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.3
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SS_DoIt_FullMethodName = "/service.SS/DoIt"
)

// SSClient is the client API for SS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SSClient interface {
	DoIt(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
}

type sSClient struct {
	cc grpc.ClientConnInterface
}

func NewSSClient(cc grpc.ClientConnInterface) SSClient {
	return &sSClient{cc}
}

func (c *sSClient) DoIt(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SS_ServiceDesc.Streams[0], SS_DoIt_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SS_DoItClient = grpc.ServerStreamingClient[Response]

// SSServer is the server API for SS service.
// All implementations must embed UnimplementedSSServer
// for forward compatibility.
type SSServer interface {
	DoIt(*Request, grpc.ServerStreamingServer[Response]) error
	mustEmbedUnimplementedSSServer()
}

// UnimplementedSSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSSServer struct{}

func (UnimplementedSSServer) DoIt(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Errorf(codes.Unimplemented, "method DoIt not implemented")
}
func (UnimplementedSSServer) mustEmbedUnimplementedSSServer() {}
func (UnimplementedSSServer) testEmbeddedByValue()            {}

// UnsafeSSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SSServer will
// result in compilation errors.
type UnsafeSSServer interface {
	mustEmbedUnimplementedSSServer()
}

func RegisterSSServer(s grpc.ServiceRegistrar, srv SSServer) {
	// If the following call pancis, it indicates UnimplementedSSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SS_ServiceDesc, srv)
}

func _SS_DoIt_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SSServer).DoIt(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SS_DoItServer = grpc.ServerStreamingServer[Response]

// SS_ServiceDesc is the grpc.ServiceDesc for SS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.SS",
	HandlerType: (*SSServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoIt",
			Handler:       _SS_DoIt_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "service.proto",
}
